trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Starting docker build
    cd $(System.DefaultWorkingDirectory)/src/StandAloneGrpcService/Server.Grpc
    docker build -t server.grpc:$(Build.BuildId) -t server.grpc:latest -f Dockerfile .

- task: ECRPushImage@1
  displayName: Push to AWS ECR
  inputs:
    awsCredentials: 'AWS ECR'
    regionName: 'eu-west-1'
    imageSource: 'imagename'
    sourceImageName: 'server.grpc'
    repositoryName: 'server.grpc'
    autoCreateRepository: true


